# Wire up travis
language: python
sudo: false

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=cover

matrix:
  include:  
    - python 3.5
      env:
        - TOXENV=py35

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
